repos:
  - repo: local
    hooks:
      - id: isek-test
        name: Run pytest
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pytest'
        language: system
        types: [python]